X                       = csvread('points.csv');
dir_base_cf_lambda      = @(d) lin_approx_accum_abs_error(X, d);
line_search_lambda      = @(func_handle, init_range, eps, max_iters)    ...
                            line_search_golden(func_handle, init_range, ...
                                               eps, max_iters, false); 
pattern_search_eps      = 1e-4;
pattern_search_iters    = 250;
line_search_eps         = 1e-4;
line_search_iters       = 100;
line_search_init_range  = [0; 8];
init_guess              = [1; 1];
pattern_basis           = [
                            1   0   -1;
                            0   1   -1
                          ];
plot_error              = true;

tic();
[x, iters, converged]   = pattern_search(dir_base_cf_lambda,      ...
                                         line_search_lambda,      ...
                                         pattern_search_eps,      ...
                                         pattern_search_iters,    ...
                                         line_search_eps,         ...
                                         line_search_iters,       ...
                                         line_search_init_range,  ...
                                         init_guess,              ...
                                         pattern_basis,           ...
                                         plot_error)
toc();

cost_gradient           = @(d) lin_approx_accum_abs_error_gradient(X, d);
steepest_descent_eps    = pattern_search_eps;
steepest_descent_iters  = pattern_search_iters;

tic();
[x, iters, converged]   = steepest_descent(dir_base_cf_lambda,      ...
                                           cost_gradient,           ...
                                           line_search_lambda,      ...
                                           steepest_descent_eps,    ...                                         
                                           steepest_descent_iters,  ...
                                           line_search_eps,         ...
                                           line_search_iters,       ...
                                           line_search_init_range,  ...
                                           init_guess,              ...
                                           plot_error)
toc();